amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456

keycloak:
  realm: test
  host: http://test:8443

logging:
  level:
    ROOT: info

mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:${mysql.port}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: ALWAYS
