# The name for the CI/CD Pipeline workflows, helps to configure and build the application, test,
#docker image and deployment application on GitHub Actions and push it to docker hub.
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'hotfix/**'
      - 'release/**'
      - 'modulos/**'
  workflow_dispatch:

env:
  # The name of the Docker Hub image, created when we created the repository to push the image.
  IMAGE_NAME: amane25/catalogo-administrativo-de-video-java

jobs:
  # Job to run the tests.
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK@21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.2
        with:
          cache-read-only: false

      - name: Run all tests
        run: ./gradlew check

  # Job to build the application.
  build:
    name: Build runner
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK@21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'adopt'
      # 3. Validate the existence of the Gradle wrapper.
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3.3.2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.2
        with:
          cache-read-only: true

      - name: Build application artifact
        run: ./gradlew clean build -x check

      - name: Set BUILD_TAG
        run: echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV

      - name: Print BUILD_TAG defined
        run: |
          echo "Branch     ---> ${{ github.head_ref || github.ref_name }}"
          echo "Run number ---> ${{ github.run_number }}"
          echo "Tag        ---> ${{ env.BUILD_TAG }}"

      - name: Log in to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & push docker image
        uses: docker/build-push-action@v5.4.0
        with:
          context: .
          push: true
          build-args: VERSION=${{ env.BUILD_TAG }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}
            ${{ env.IMAGE_NAME }}:latest